-- Haggle offers: a customer proposes a per-unit price for a product,
-- the vendor accepts/rejects/counters, the customer can only counter back
-- (never accept directly — only the vendor's own accept ends a
-- negotiation in the customer's favor). Once accepted, the customer gets
-- that price automatically applied when they add the product to cart;
-- placing the order that uses it marks the haggle 'used' so the price
-- reverts to the listed price for next time. Visible only to the
-- customer who made it and the vendor who owns the stall — enforced here
-- via RLS, not just hidden in the UI.

create table if not exists public.haggle_offers (
  id              bigint generated by default as identity primary key,
  product_id      bigint not null references public.products(id) on delete cascade,
  stall_id        bigint not null references public.stalls(id) on delete cascade,
  customer_id     uuid not null references auth.users(id) on delete cascade,
  vendor_id       uuid not null references auth.users(id) on delete cascade,
  listed_price    numeric(10,2) not null,
  unit            text,
  current_price   numeric(10,2) not null,
  last_offered_by text not null check (last_offered_by in ('customer', 'vendor')),
  status          text not null default 'pending'
                    check (status in ('pending', 'accepted', 'rejected', 'cancelled', 'used')),
  used_order_id   bigint references public.orders(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists haggle_offers_customer_idx on public.haggle_offers(customer_id);
create index if not exists haggle_offers_vendor_idx on public.haggle_offers(vendor_id);
-- Looked up on every product page view and every add-to-cart, so this is
-- the hot path: "does this customer have a live haggle on this product?"
create index if not exists haggle_offers_product_customer_idx
  on public.haggle_offers(product_id, customer_id);

create or replace function public.touch_haggle_offers_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_haggle_offers_updated_at on public.haggle_offers;
create trigger trg_haggle_offers_updated_at
  before update on public.haggle_offers
  for each row execute function public.touch_haggle_offers_updated_at();

alter table public.haggle_offers enable row level security;

-- Only the two parties involved can see a haggle at all.
drop policy if exists "haggle visible to customer" on public.haggle_offers;
create policy "haggle visible to customer"
  on public.haggle_offers for select
  using (auth.uid() = customer_id);

drop policy if exists "haggle visible to vendor" on public.haggle_offers;
create policy "haggle visible to vendor"
  on public.haggle_offers for select
  using (auth.uid() = vendor_id);

-- Only the customer can start one, and only for themselves.
drop policy if exists "customer creates haggle" on public.haggle_offers;
create policy "customer creates haggle"
  on public.haggle_offers for insert
  with check (auth.uid() = customer_id and last_offered_by = 'customer' and status = 'pending');

-- Customer may only touch a still-open negotiation of their own — to
-- counter (it was the vendor's turn) or withdraw their own unanswered
-- offer (it was already their turn). The application enforces which
-- fields actually change in which case; this just gates row ownership
-- and that the negotiation hasn't already concluded.
drop policy if exists "customer updates own pending haggle" on public.haggle_offers;
create policy "customer updates own pending haggle"
  on public.haggle_offers for update
  using (auth.uid() = customer_id and status = 'pending');

-- Customer marks their own accepted-but-unused haggle 'used' at checkout.
drop policy if exists "customer consumes accepted haggle" on public.haggle_offers;
create policy "customer consumes accepted haggle"
  on public.haggle_offers for update
  using (auth.uid() = customer_id and status = 'accepted');

-- Vendor may only respond when it's their turn on an open negotiation —
-- accept, reject, or counter.
drop policy if exists "vendor updates own pending haggle" on public.haggle_offers;
create policy "vendor updates own pending haggle"
  on public.haggle_offers for update
  using (auth.uid() = vendor_id and status = 'pending' and last_offered_by = 'customer');
