-- =====================================================
-- Migration: create contact_messages table for the landing
-- page's Contact form (landingpage-website/contact.html)
--
-- The form previously faked a success message client-side and
-- discarded whatever the visitor typed. This gives it somewhere
-- real to land: a table only readable from the Supabase
-- dashboard (service role bypasses RLS) — the public anon key
-- can INSERT but never SELECT/UPDATE/DELETE, so a submitted
-- message can't be read back or tampered with by other visitors.
--
-- How to apply:
--   1. Open https://supabase.com/dashboard
--   2. Project: "PalengkeHub" (jjpgmpufwpbgqjzqymvj)
--   3. SQL Editor → New query → paste this entire file → Run
--   4. Table Editor → contact_messages, to read submissions
-- =====================================================

create table if not exists public.contact_messages (
  id          bigint generated by default as identity primary key,
  name        text not null,
  email       text not null,
  subject     text not null,
  message     text not null,
  status      text not null default 'new' check (status in ('new','read','replied')),
  created_at  timestamptz not null default now()
);

create index if not exists contact_messages_created_at_idx
  on public.contact_messages (created_at desc);

alter table public.contact_messages enable row level security;

-- Any visitor (logged in or not) can submit a message...
drop policy if exists "Anyone can submit a contact message" on public.contact_messages;
create policy "Anyone can submit a contact message"
  on public.contact_messages for insert
  to anon, authenticated
  with check (true);

-- ...but nobody can read, edit, or delete them through the public
-- API. No select/update/delete policy exists for anon/authenticated
-- on purpose — only the dashboard (service role) can see this table.

notify pgrst, 'reload schema';

-- ── Verify ───────────────────────────────────────────────
select column_name, data_type from information_schema.columns
where table_schema = 'public' and table_name = 'contact_messages'
order by ordinal_position;
