-- =====================================================
-- Migration: create price_anomalies table
-- Reason: new price anomaly enforcement feature. When a vendor tries
-- to save a price far above market average, the app warns them and,
-- if they proceed anyway, records it here so admin can review it.
-- Admin can also manually flag a price directly. Unresolved flags get
-- a daily reminder and, after 3 days, the vendor's whole stall is
-- deactivated (see create-price-anomaly-cron-job.sql) until admin
-- reactivates it.
--
-- Depends on: add-price-anomaly-notification-type.sql (run first —
-- the cron job and app code both write 'price_anomaly' notifications).
--
-- How to apply:
--   1. Open https://supabase.com/dashboard
--   2. Project: "PalengkeHub" (jjpgmpufwpbgqjzqymvj)
--   3. SQL Editor → New query → paste this entire file → Run
-- =====================================================

create table if not exists public.price_anomalies (
  id                bigint generated by default as identity primary key,
  product_id        bigint not null references public.products(id) on delete cascade,
  stall_id          bigint not null references public.stalls(id) on delete cascade,
  vendor_id         uuid not null references auth.users(id) on delete cascade,
  unit              text,
  flagged_price     numeric(10,2) not null,
  market_avg_price  numeric(10,2),
  deviation_pct     numeric(6,1),
  source            text not null check (source in ('auto', 'admin_manual')),
  status            text not null default 'pending'
                      check (status in ('pending', 'resolved', 'deactivated')),
  admin_note        text,
  flagged_by        uuid references auth.users(id) on delete set null,
  flagged_at        timestamptz not null default now(),
  deadline          timestamptz not null default (now() + interval '3 days'),
  last_warning_at   timestamptz,
  resolved_at       timestamptz
);

create index if not exists price_anomalies_product_idx on public.price_anomalies (product_id);
create index if not exists price_anomalies_stall_idx on public.price_anomalies (stall_id);
create index if not exists price_anomalies_vendor_idx on public.price_anomalies (vendor_id);
create index if not exists price_anomalies_status_idx on public.price_anomalies (status);

alter table public.price_anomalies enable row level security;

-- Vendor sees only their own flags (auto or admin-manual, either way
-- it's about their own product).
drop policy if exists "Vendors can view own price anomalies" on public.price_anomalies;
create policy "Vendors can view own price anomalies" on public.price_anomalies
  for select
  using (vendor_id = auth.uid());

-- Vendor's own client inserts the record when THEY confirm past the
-- warning dialog — never on the vendor's behalf by anyone else, and
-- always starts 'pending'.
drop policy if exists "Vendors can insert own auto anomaly" on public.price_anomalies;
create policy "Vendors can insert own auto anomaly" on public.price_anomalies
  for insert
  with check (vendor_id = auth.uid() and source = 'auto' and status = 'pending');

-- Vendor fixing their own price flips pending/deactivated -> resolved.
-- Nothing else about a vendor's own flag is theirs to change.
drop policy if exists "Vendors can resolve own anomaly" on public.price_anomalies;
create policy "Vendors can resolve own anomaly" on public.price_anomalies
  for update
  using (vendor_id = auth.uid() and status in ('pending', 'deactivated'))
  with check (vendor_id = auth.uid() and status = 'resolved');

-- Admin has full visibility and control — manual flags, review,
-- reactivation bookkeeping.
drop policy if exists "Admins can view all price anomalies" on public.price_anomalies;
create policy "Admins can view all price anomalies" on public.price_anomalies
  for select
  using (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role = 'admin'));

drop policy if exists "Admins can insert price anomalies" on public.price_anomalies;
create policy "Admins can insert price anomalies" on public.price_anomalies
  for insert
  with check (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role = 'admin'));

drop policy if exists "Admins can update price anomalies" on public.price_anomalies;
create policy "Admins can update price anomalies" on public.price_anomalies
  for update
  using (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role = 'admin'));

notify pgrst, 'reload schema';

-- ── Verify ───────────────────────────────────────────────
select column_name, data_type from information_schema.columns
where table_schema = 'public' and table_name = 'price_anomalies'
order by ordinal_position;
