-- =====================================================
-- Migration: create price_history table
-- Reason: Price Monitor section crashes (PGRST205)
--         because the table 'price_history' does not
--         exist in the database yet.
--
-- How to apply:
--   1. Open https://supabase.com/dashboard
--   2. Project: "PalengkeHub" (jjpgmpufwpbgqjzqymvj)
--   3. Go to SQL Editor → click "New query"
--   4. Paste this entire file → Run
--   5. The Price Monitor section will then load data.
-- =====================================================

create table if not exists public.price_history (
  id              bigint      generated by default as identity
                  primary key,
  product_id      bigint      references public.products not null,
  previous_price  numeric(10,2),
  new_price       numeric(10,2)  not null,
  changed_at      timestamptz    not null default now(),
  changed_by      bigint         references public.profiles
);

-- Indexes for performance
create index if not exists price_history_product_id_idx
  on public.price_history (product_id);
create index if not exists price_history_changed_at_idx
  on public.price_history (changed_at desc);

-- Enable realtime so the admin panel picks up changes
alter publication supabase_realtime add table public.price_history;

-- If you want to seed historical entries from existing product prices:
-- insert into public.price_history (product_id, previous_price, new_price)
-- select id, price as previous_price, price as new_price from public.products;