-- =====================================================
-- Migration: create price_history table + auto-record trigger
-- Reason: Price Monitoring / Price Change History are empty
--         because (1) the table doesn't exist (PGRST205) and
--         (2) no code ever wrote rows into it.
--
-- This fixes BOTH: creates the table AND adds a trigger that
-- automatically records old→new price every time a product's
-- price changes — from any app (vendor, admin web, mobile).
--
-- How to apply:
--   1. Open https://supabase.com/dashboard
--   2. Project: "PalengkeHub" (jjpgmpufwpbgqjzqymvj)
--   3. SQL Editor → New query → paste this entire file → Run
--   4. Refresh the admin panel. History starts recording on
--      the next price change.
-- =====================================================

-- ── 1. Table ────────────────────────────────────────────────
create table if not exists public.price_history (
  id              bigint generated by default as identity primary key,
  product_id      bigint not null references public.products(id) on delete cascade,
  previous_price  numeric(10,2),
  new_price       numeric(10,2) not null,
  changed_at      timestamptz not null default now(),
  changed_by      uuid references auth.users(id) on delete set null
);

create index if not exists price_history_product_id_idx
  on public.price_history (product_id);
create index if not exists price_history_changed_at_idx
  on public.price_history (changed_at desc);

-- ── 2. Auto-record trigger (the important part) ─────────────
create or replace function public.record_price_change()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  -- Only log when the price actually changed
  if new.price is distinct from old.price then
    insert into public.price_history (product_id, previous_price, new_price, changed_by)
    values (new.id, old.price, new.price, auth.uid());
  end if;
  return new;
end;
$$;

drop trigger if exists trg_record_price_change on public.products;
create trigger trg_record_price_change
  after update on public.products
  for each row execute function public.record_price_change();

-- ── 3. Access + realtime ────────────────────────────────────
alter table public.price_history enable row level security;

drop policy if exists "Anyone can view price history" on public.price_history;
create policy "Anyone can view price history"
  on public.price_history for select
  using (true);

drop policy if exists "Authenticated can insert price history" on public.price_history;
create policy "Authenticated can insert price history"
  on public.price_history for insert
  to authenticated
  with check (true);

alter publication supabase_realtime add table public.price_history;

notify pgrst, 'reload schema';

-- ── 4. Verify ───────────────────────────────────────────────
select column_name, data_type from information_schema.columns
where table_schema = 'public' and table_name = 'price_history'
order by ordinal_position;

-- Optional seed: one baseline row per existing product so the
-- graph isn't empty before the first real price change:
-- insert into public.price_history (product_id, previous_price, new_price)
-- select id, price, price from public.products;