-- =====================================================
-- Migration: create stall_locations table + verification queue support
--
-- Replaces the dead-end location UI in VendorProfileScreen (a
-- `latitude`/`longitude` state pair with nowhere real to save to —
-- `stalls` has no such columns) with a proper capture pipeline:
-- multi-sample GPS averaging, an accuracy confidence value, an
-- admin-review flag, and a real history table so a re-registered
-- stall doesn't silently overwrite its previous pin.
--
-- One row per capture, not one row per stall — `is_current` marks
-- the row customers/admins should read "now"; older rows for the
-- same stall stay in place as history when a stall re-registers.
--
-- How to apply:
--   1. Open https://supabase.com/dashboard
--   2. Project: "PalengkeHub" (jjpgmpufwpbgqjzqymvj)
--   3. SQL Editor → New query → paste this entire file → Run
-- =====================================================

create table if not exists public.stall_locations (
  id                  bigint generated by default as identity primary key,
  stall_id            bigint not null references public.stalls(id) on delete cascade,

  lat                 numeric(10,7) not null,
  lng                 numeric(10,7) not null,
  accuracy_meters     numeric(6,2),  -- null for a manual/no-GPS placement, never a fabricated number

  captured_by         text not null check (captured_by in ('vendor','admin')),
  captured_at         timestamptz not null default now(),
  capture_method      text not null default 'gps' check (capture_method in ('gps', 'manual_no_gps')),
  manually_adjusted   boolean not null default false,

  verified_by_admin   boolean not null default false,
  verified_at         timestamptz,
  reregister_reason   text,

  -- Exactly one current row per stall (partial unique index below);
  -- every earlier capture for that stall stays in the table with
  -- is_current = false as history, per the "don't silently overwrite
  -- a disputed pin" requirement.
  is_current          boolean not null default true,

  created_at          timestamptz not null default now()
);

create unique index if not exists stall_locations_one_current_per_stall
  on public.stall_locations (stall_id)
  where is_current;

create index if not exists stall_locations_stall_id_idx
  on public.stall_locations (stall_id);

create index if not exists stall_locations_review_queue_idx
  on public.stall_locations (accuracy_meters desc)
  where is_current and (verified_by_admin = false or accuracy_meters > 15);

-- ── Access ───────────────────────────────────────────────
alter table public.stall_locations enable row level security;

-- Everyone can read the current pin for a stall — it's what powers
-- the customer-facing distance + directions button, no login needed.
drop policy if exists "Anyone can view current stall locations" on public.stall_locations;
create policy "Anyone can view current stall locations"
  on public.stall_locations for select
  using (true);

-- A vendor can insert a capture for their own stall; admins can
-- insert for any stall (the "capturedBy: admin" path in the spec).
drop policy if exists "Vendor can insert own stall location" on public.stall_locations;
create policy "Vendor can insert own stall location"
  on public.stall_locations for insert
  to authenticated
  with check (
    exists (
      select 1 from public.stalls
      where stalls.id = stall_id and stalls.vendor_id = auth.uid()
    )
    or exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Only an admin can flip verified_by_admin / reregister_reason /
-- is_current on someone else's row (the approve / adjust-and-approve
-- / flag-for-re-registration actions). A vendor updating their own
-- freshly-inserted row (rare, e.g. a client-side retry) is allowed
-- too, but they can't grant their own verification.
drop policy if exists "Admin can update stall locations" on public.stall_locations;
create policy "Admin can update stall locations"
  on public.stall_locations for update
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

notify pgrst, 'reload schema';

-- ── Verify ───────────────────────────────────────────────
select column_name, data_type from information_schema.columns
where table_schema = 'public' and table_name = 'stall_locations'
order by ordinal_position;
